version: '3'
services:
    assembly:
        build:
            context: ./Assembly
            dockerfile: Dockerfile
        volumes:
            - 'CommonFiles:/usr/src/app/App42PaaS-Java-MySQL-Sample/target'
        depends_on:
            - base
    prod:
        build:
            context: ./Production
            dockerfile: Dockerfile
        ports:
             - '8080:8080'
        depends_on:
             - assembly
        volumes:
            - 'CommonFiles:/usr/local/tomcat/webapps'
    base:
        build:
            context: ./Base
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_DATABASE: 'java_db'
            MYSQL_ROOT_PASSWORD: '_JavaAdmin@_'
        ports:
             - '3306:3306'

volumes:
    CommonFiles:
