version: '3'
services:
    assembly:
        build:
            context: ./Assembly
            dockerfile: Dockerfile
        volumes:
            - 'CommonFiles:/usr/src/app/App42PaaS-Java-MySQL-Sample/target'
    prod:
        build:
            context: ./Production
            dockerfile: Dockerfile
        ports:
             - '8080:8080'
        depends_on:
             - assembly
        volumes:
            - 'CommonFiles:/usr/local/tomcat/webapps'
    base:
        build:
            context: ./Production
            dockerfile: Dockerfile
        ports:
             - '8080:8080'
        depends_on:
        
volumes:
    CommonFiles:
